[profile.default]
solc = "0.8.15"
src = 'src'
script = 'script'
out = 'out'
libs = ['lib']
bytecode_hash = "none"
optimizer_runs = 1000000

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config